@Library('my-shared-library') _

pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                sayHello('Meghraj')
            }
        }

        stage('Build') {
            steps {
                echo 'Building application...'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing application...'
            }
        }
    }
}